/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/N6Pvo7ehj7n
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Work from './work';
import Skills from './skills';
import Contact from './contact';
import Hero from './hero';

const Home = () => {
  return (
    <>
      <Hero />
      <Work />
      <Skills />
      <Contact />
    </>
  );
};

export default Home;
