name: Build and deploy app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CI/CD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/rowanpaulflynn
            git fetch --all
            git reset --hard origin/main
            docker stop rowanpaulflynn
            docker build . -t rowanpaulflynn
            docker run -e VIRTUAL_HOST=rowanpaulflynn.com -e LETSENCRYPT_HOST=rowanpaulflynn.com -d --name rowanpaulflynn rowanpaulflynn
